export const FETCH_LOGIN_USER = '@@USER//FETCH_LOGIN';
export const FETCH_LOGIN_USER_SUCCESS = '@@USER//FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_USER_ERROR = '@@USER//FETCH_LOGIN_ERROR';
export const FETCH_LOGOUT_USER = '@@USER//FETCH_LOGOUT';
export const FETCH_LOGOUT_USER_SUCCESS = '@@USER//FETCH_LOGOUT_SUCCESS';
export const FETCH_LOGOUT_USER_ERROR = '@@USER//FETCH_LOGOUT_ERROR';